spring:
  application:
    name: hotel-san-francisco-api

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HotelHikariPool

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

        jdbc:
          time_zone: ${APP_TIMEZONE}

        order_inserts: true
        order_updates: true
        batch_size: 25

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    out-of-order: false

  cache:
    type: caffeine

    cache-names:
      - tiposHabitacion
      - habitaciones
      - canales
      - tiposDocumento
      - metodosPago
      - tiposServicio
      - categoriasProducto
      - horarios
      - proveedores

    caffeine:
      spec: maximumSize=${CACHE_MAX_SIZE},expireAfterWrite=${CACHE_EXPIRE_AFTER_WRITE},recordStats

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
    jwt:
      secret-key: ${JWT_SECRET_KEY:default_key}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 min (en ms)
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 días (en ms)

app:
  cookie:
    secure: ${APP_COOKIE_SECURE:false}

  reserva:
    online:
      usuario-sistema-id: ${RESERVA_ONLINE_USUARIO_ID:1}
      canal-nombre: ${RESERVA_ONLINE_CANAL_NOMBRE:ONLINE}

server:
  port: ${SERVER_PORT}

  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org.hibernate.SQL: ${LOG_LEVEL_SQL}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_BIND}
    com.sanfrancisco.api: ${LOG_LEVEL_APP}
    org.springframework.security: ${LOG_LEVEL_SECURITY}
    org.flywaydb: ${LOG_LEVEL_FLYWAY}

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"