package com.sanfrancisco.api.modules.notificaciones.enums;

public enum EmailTemplateKey {
    RESERVATION_CONFIRMATION,
    PAYMENT_CONFIRMATION,
    RESERVATION_CANCELLATION,
    RESERVATION_RESCHEDULED,
    STAY_REMINDER,
    STAY_CHECKOUT,
    PASSWORD_RESET,
    EMAIL_VERIFICATION_CODE,
    REQUEST_STATUS_CHANGED
}

